---
title: "admixture plotting"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Plotting for K=2
```{r}
tbl=read.table("~/Cirsium/admixture/cirsium_filtered_A/cirsium_A.2.Q")

popGroups = read.table("~/Cirsium/admixture/cirsium_filtered/taxa.txt", col.names=c("Ind", "Region"))

mergedAdmWithPopGroups = cbind(popGroups, tbl)

ordered_by_reg = mergedAdmWithPopGroups[order(mergedAdmWithPopGroups$Region),]

barplot(t(as.matrix(subset(ordered_by_reg, select=V1:V2))), col=rainbow(2), border=NA, names.arg=c(ordered_by_reg$Region), cex.names=0.7, las=2, main="K=2, organized by region")

ordered_by_sim = mergedAdmWithPopGroups[order(mergedAdmWithPopGroups$V1),]


barplot(t(as.matrix(subset(ordered_by_sim, select=V1:V2))), col=rainbow(2), border=NA, names.arg=c(ordered_by_sim$Region), cex.names=0.3, las=2, main="K=2, organized by population group")

```

## Plotting for K=3
```{r}
tbl=read.table("~/Cirsium/admixture/cirsium_filtered_A/cirsium_A.3.Q")

popGroups = read.table("~/Cirsium/admixture/cirsium_filtered/taxa.txt", col.names=c("Ind", "Region"))

mergedAdmWithPopGroups = cbind(popGroups, tbl)

ordered_by_reg = mergedAdmWithPopGroups[order(mergedAdmWithPopGroups$Region),]

barplot(t(as.matrix(subset(ordered_by_reg, select=V1:V3))), col=rainbow(3), border=NA, names.arg=c(ordered_by_reg$Region), cex.names=0.7, las=2, main="K=3, organized by region")

ordered_by_sim = mergedAdmWithPopGroups[order(mergedAdmWithPopGroups$V1),]


barplot(t(as.matrix(subset(ordered_by_sim, select=V1:V3))), col=rainbow(3), border=NA, names.arg=c(ordered_by_sim$Region), cex.names=0.3, las=2, main="K=3, organized by population group")
```
## Plotting for K=4
```{r}
tbl=read.table("~/Cirsium/admixture/cirsium_filtered_A/cirsium_A.4.Q")

popGroups = read.table("~/Cirsium/admixture/cirsium_filtered/taxa.txt", col.names=c("Ind", "Region"))

mergedAdmWithPopGroups = cbind(popGroups, tbl)

ordered_by_reg = mergedAdmWithPopGroups[order(mergedAdmWithPopGroups$Region),]

barplot(t(as.matrix(subset(ordered_by_reg, select=V1:V4))), col=rainbow(4), border=NA, names.arg=c(ordered_by_reg$Region), cex.names=0.7, las=2, main="K=4, organized by region")

ordered_by_sim = mergedAdmWithPopGroups[order(mergedAdmWithPopGroups$V1),]

barplot(t(as.matrix(subset(ordered_by_sim, select=V1:V4))), col=rainbow(4), border=NA, names.arg=c(ordered_by_sim$Region), cex.names=0.3, las=2, main="K=4, organized by population group")
```

## Plotting for K=5
```{r}
tbl=read.table("~/Cirsium/admixture/cirsium_filtered_A/cirsium_A.5.Q")

popGroups = read.table("~/Cirsium/admixture/cirsium_filtered/taxa.txt", col.names=c("Ind", "Region"))

mergedAdmWithPopGroups = cbind(popGroups, tbl)

ordered_by_reg = mergedAdmWithPopGroups[order(mergedAdmWithPopGroups$Region),]

barplot(t(as.matrix(subset(ordered_by_reg, select=V1:V5))), col=rainbow(5), border=NA, names.arg=c(ordered_by_reg$Region), cex.names=0.7, las=2, main="K=5, organized by region")

ordered_by_sim = mergedAdmWithPopGroups[order(mergedAdmWithPopGroups$V1),]

barplot(t(as.matrix(subset(ordered_by_sim, select=V1:V5))), col=rainbow(4), border=NA, names.arg=c(ordered_by_sim$Region), cex.names=0.3, las=2, main="K=5, organized by population group")

```